<?php

namespace Tests\Unit;

use App\Database\PDODatabaseConnection;
use App\Database\PDOQueryBuilder;
use App\Helpers\Config;
use PHPUnit\Framework\TestCase;

class PDOQueryBuilderTest extends TestCase
{
    private $queryBuilder;
    public function setUp(): void
    {
        $pdoConnection= new PDODatabaseConnection($this->getConfig());
        $this->queryBuilder= new PDOQueryBuilder($pdoConnection->connect());

        parent::setUp(); // TODO: Change the autogenerated stub
    }
    public function tearDown(): void
    {
        $this->queryBuilder->truncatAllTable();
        parent::tearDown(); // TODO: Change the autogenerated stub
    }

    public function testItCanCreateData()
    {
       $result=$this->insertIntoDb();
       $this->assertIsInt($result);
       $this->assertGreaterThan(0,$result);
    }
    public function testItCanUpdateData()
    {
       $this->insertIntoDb();
       $result=$this->queryBuilder
            ->table('bugs')
            ->where('user', 'Behnoosh')
            ->update(['email' => 'euruse@gmail.com']);
        $this->assertEquals(1, $result);
    }
    public function testItCanDeleteRecord()
    {
        $this->insertIntoDb();
        $this->insertIntoDb();
        $this->insertIntoDb();
        $this->insertIntoDb();

        $result= $this->queryBuilder
            ->table('bugs')
            ->where('user', 'Behnoosh')
            ->delete();
        $this->assertEquals(4, $result);
    }
    private function insertIntoDb()
    {
        $data =[
            'name'=>'First Bug',
            'link'=>'www.link.com',
            'user' => 'Behnoosh',
            'email'=>'behnoosh@link.com'
        ];
        $result=$this->queryBuilder->table('bugs')->create($data);
        return $result;
    }
    private function getConfig()
    {
        return Config::get('database','pdo_testing');
    }
}
